### ISSUE TITLE
📟 Organizar imágenes en carpetas

### ISSUE THREAD

**Issue by anattolia** [enflujo/enflujo-haciendocaminos#59]
Organizar imágenes en carpetas: comprimir, hacer dos tamaños de imágenes y organizar archivos en carpetas.

**Comment by juanmi30** [comment]
Faltan tres imágenes: Buritaca_2-4 / proyecto 56
Falta imágen ManuelQuintin_1 / proyecto 58
Imágenes EscuelaMarmato_1 y EscuelaMarmato_2 están corrompidas / proyecto 67
Imágenes Capitalización_1-5 están corrompidas / proyecto 69
Imágenes GenealogiasViolencia_1-8 están corrompidas / proyecto 70
Imágenes FuturosEnergéticos_1-3 están corrompidas / proyecto 71
Imágenes RegimenesDeIntervención_1-2 están corrompidas / proyecto 73
