### ISSUE TITLE
🖼️ Producir y llenar datos e imágenes SEO

### ISSUE THREAD

**Issue by Juliansintilde** [enflujo/enflujo-haciendocaminos#62]

**Comment by Juliansintilde** [comment]
#aiuda @anattolia @1cgonza  puse los archivos del favicon e iconos pero cuando cargo la página no cambia

<img width="803" alt="image" src="https://github.com/enflujo/enflujo-haciendocaminos/assets/42554838/536d835d-e481-4b4e-9cb9-9c440cfbcbaa">


<img width="1400" alt="image" src="https://github.com/enflujo/enflujo-haciendocaminos/assets/42554838/8031a8d9-9a4a-4814-a27c-106f3aa687fa">

<img width="1277" alt="image" src="https://github.com/enflujo/enflujo-haciendocaminos/assets/42554838/4d8562b5-34be-4554-947e-e8d62557c963">

<img width="729" alt="image" src="https://github.com/enflujo/enflujo-haciendocaminos/assets/42554838/e64d6325-0372-4988-a95e-0aa6ba1af18c">

**Comment by Juliansintilde** [comment]
@1cgonza @anattolia 

Funcionó pero con esta ruta:

<img width="779" alt="image" src="https://github.com/enflujo/enflujo-haciendocaminos/assets/42554838/769f3d3e-9236-4bac-a361-345ce0840d0b">


¿Se vale así?

**Comment by 1cgonza** [comment]
@Juliansintilde ya veo cual es el problema. La URL que se está construyendo antes de sus cambios es:

`https://enflujo.github.io/enflujo-haciendocaminos/favicon.ico`: Pille que es la del servidor y no la local que sería: `http://localhost:4321/enflujo-haciendocaminos/favicon.ico`. 

**En ningún caso la URL debe tener `/estaticos` como le explicaba, esto en localhost funciona pero en el servidor no.**

La que necesitamos para que funcione en ambos localhost y servidor es:
`/enflujo-haciendocaminos/favicon.ico`. 

De momento hay un problema para construir esta URL en la forma más estable, pero por el momento, solo cambie estas dos líneas, con eso puede probar las imágenes de manera local y va a funcionar en el servidor, la solución que propone solo funciona local: 

```html
<link rel="icon" href={`${import.meta.env.BASE_URL}/favicon.ico`} sizes="32x32" />
<link rel="icon" href={`${import.meta.env.BASE_URL}/favicon.svg`} type="image/svg+xml" />
```
