### ISSUE TITLE
🐛 Gusanito del menú 'Proyectos' se queda pegado

### ISSUE THREAD

**Issue by Juliansintilde** [enflujo/enflujo-haciendocaminos#67]
Pasa esto cuando uno esconde el menú:

<img width="545" alt="image" src="https://github.com/enflujo/enflujo-haciendocaminos/assets/42554838/cc6845ca-85b7-47b3-8358-4dc14aeac8b7">

--

Intenté cambiarlo con el absolute pero no logré corregirlo sin hacerlo desaparecer de todas partes.

**Comment by 1cgonza** [comment]
resuelto en [3758a3c](https://github.com/enflujo/enflujo-haciendocaminos/commit/3758a3c07a2fccd5241bd83c223fa4481cc413a2)
