### ISSUE TITLE
💀  Imágenes que faltan o están corrompidas

### ISSUE THREAD

**Issue by anattolia** [enflujo/enflujo-haciendocaminos#73]
Consideraciones:

Faltan tres imágenes: Buritaca_2-4 / proyecto 56
Falta imágen ManuelQuintin_1 / proyecto 58
Imágenes EscuelaMarmato_1 y EscuelaMarmato_2 están corrompidas / proyecto 67
Imágenes Capitalización_1-5 están corrompidas / proyecto 69
Imágenes GenealogiasViolencia_1-8 están corrompidas / proyecto 70
Imágenes FuturosEnergéticos_1-3 están corrompidas / proyecto 71
Imágenes RegimenesDeIntervención_1-2 están corrompidas / proyecto 73

**Comment by 1cgonza** [comment]
Esto en que quedó? o se puede borrar?
