### ISSUE TITLE
✍🏼 Correcciones de Lucho

### ISSUE THREAD

**Issue by Juliansintilde** [enflujo/enflujo-haciendocaminos#74]
- [x] Créditos:
- Investigación:
Profesores del Departamento de Antropología, Facultad de Ciencias Sociales
Daniel A Medina

> En realidad sería los profesores y daniel A que es el asistente graduado que todos son del departamento que es de la facultad.

- [x] - Apoyo: 

Comunicaciones y Posicionamiento, Facultad de Ciencias Sociales

> https://cienciassociales.uniandes.edu.co/

- [x] - Diseño conceptual y mediación:

Colectivo Humanidad Digital

> https://humanidad.digital/

- [x] - Desarrollo de la visualización:

Laboratorio En Flujo

- [x] Universidad de los Andes

2024

- [x] Una cosa: en el cabezote del menú haría falta el logo de Los Andes y en el texto

> [2:51 p. m., 6/3/2024] Luis Antonio Silva: Una cosa: en el cabezote del menú haría falta el logo de Los Andes y en el texto
> [2:51 p. m., 6/3/2024] Luis Antonio Silva: DEPARTAMENTO DE ANTROPOLOGÍA | 60 AÑOS HACIENDO CAMINOS

> Pero vi este también entonces así las cosas puede quedar arriba 60 años haciendo caminos

![image](https://github.com/enflujo/enflujo-haciendocaminos/assets/42554838/aef9f591-734f-49a8-8a35-be53acf2f06b)

- [x] y acá podría quedar solo uniandes antropologia ese logo.

![image](https://github.com/enflujo/enflujo-haciendocaminos/assets/42554838/74d79350-8b9f-4583-ad3b-48c61a8d2842)

- [x]  Están en el texto de la presentación, pendientes.

- [x] Y en el documento quedaron las descripciones de las áreas: https://uniandes-my.sharepoint.com/:x:/g/personal/a_ulloag_uniandes_edu_co/EXYMF4ClecFDlq5cXXATOVUBdIPVlisb1tID1mt-JtYEGA?email=la.silva1243%40uniandes.edu.co&e=U13lKD

- [x] Aquí faltaría separar las dos últimas: sí ve que están separadas por coma pero se lee como si fueran cateogrías diferentes?

![image](https://github.com/enflujo/enflujo-haciendocaminos/assets/42554838/713cb7b4-aa04-4a20-b697-8d7a524978c1)

**Comment by anattolia** [comment]
@Juliansintilde ¿Esto ya quedó? ¿Borramos el issue?

**Comment by Juliansintilde** [comment]
@anattolia 
Si los últimos dos puntos ya están, sí. (que creo que entre @1cgonza y tú los estaban haciendo, ¿cierto?)
Los demás ya están 👍🏼
