### ISSUE TITLE
🪰 Correcciones Lucho 14-03-24

### ISSUE THREAD

**Issue by anattolia** [enflujo/enflujo-haciendocaminos#81]
- [x] Botones explícitos y horizontales en "Proyectos" y "Egresados". **-> @1cgonza ¿A qué se refieren con "horizontales"? ¿Que no estén puestos uno encima del otro?**

- [x] Cambiar nombre de "Objetos" por "Objetos de análisis" / Se despintó, no sé si cambiaron el nombre de la columna. **-> @1cgonza No entiendo, ¿qué se despintó? Yo le cambié el nombre al campo en la ficha pero ¿qué falta?**

- [ ] Falta revisar locaciones cuando no hay municipio, o departamento o país. **-> Esto está en otro issue.**

- [x] Alguna interacción dentro del mapa en las áreas resaltadas

- [x] #91

**Comment by Juliansintilde** [comment]
el primer punto está trabajado en el #82
