### ISSUE TITLE
:accordion: falta imagen de SEO

### ISSUE THREAD

**Issue by 1cgonza** [enflujo/enflujo-haciendocaminos#84]
La imagen en `/estaticos/imagen_OG.jpg` es la de EnFlujo: [imagen_OG.jpg](https://github.com/enflujo/enflujo-haciendocaminos/blob/main/estaticos/imagen_OG.jpg) - toca hacer una.

**Comment by 1cgonza** [comment]
Ya vi que quedó en `_1200seo_3_comp.jpeg` pero porfa no usar un pantallazo de "Amalia Uribe" sino una imagen que pueda ser general a todo el proyecto.

**Comment by Juliansintilde** [comment]
@1cgonza Me parece que la ficha desplegada es ilustrativa. Es decir, justamente hice clic en un elemento como para hacer una especie de abrebocas. **Ahora bien**, ejej, la puedo cambiar, claro, pero era de aposta, :D
